name: CI
on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
lint:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.10'
- name: Install
run: pip install -r requirements.txt
- name: Run accessibility checks
run: python -m locaccess.cli check sample || true
